import React, { Component } from "react";

import { Grid, Paper, Button, TextField, Switch, 
         FormLabel, FormControlLabel, IconButton } from '@material-ui/core';
import FileCopyRoundedIcon from '@material-ui/icons/FileCopyRounded';
import ReplayRoundedIcon from '@material-ui/icons/ReplayRounded';

import Snackbar from '@material-ui/core/Snackbar';
import MuiAlert from '@material-ui/lab/Alert';

import { withStyles } from '@material-ui/core/styles';

import Progress from './ProgressBar';
import AlertInputValidationDialog from "./AlertInputValidationDialog";

import AceEditor from 'react-ace';
import 'brace/ext/language_tools';
import "ace-builds/src-noconflict/mode-golang";
import "ace-builds/src-noconflict/mode-javascript";
import "ace-builds/src-noconflict/theme-github";


const styles = theme => ({
  root: {
    flexGrow: 1,
  },
  paper: {
    marginTop: theme.spacing(1),
    padding: theme.spacing(1),
    minHeight: "300px",
  },
  button: {
    color: "white",
    backgroundColor: theme.palette.info.dark,
    marginRight: theme.spacing(1),

  }
});

function Alert(props) {
  return <MuiAlert elevation={6} variant="filled" {...props} />;
}

class FormContainer extends Component {
  
  constructor(props) {
    super(props);

    this.state = {
      showProgress: false, 
      extjson: false, 
      minIntSize: true,
      truncateInt: false,
      topname: "AutoGenerated",
      output: "", 
      content: "",
      openAlert: false,
      openValidationAlert: false,
      msgValidationAlert: "",
    };

    this.handleSwitchExtJSON = this.handleSwitchExtJSON.bind(this);
    this.handleSwitchMinInt = this.handleSwitchMinInt.bind(this);
    this.handleSwitchTruncInt = this.handleSwitchTruncInt.bind(this);
    this.handleAlertClick = this.handleAlertClick.bind(this); 
    this.handleAlertClose = this.handleAlertClose.bind(this);
    this.handleCopyClipboard = this.handleCopyClipboard.bind(this);
    this.handleTextFieldTopName = this.handleTextFieldTopName.bind(this);
    this.handleCodeChange = this.handleCodeChange.bind(this);
    this.handleFormSubmit = this.handleFormSubmit.bind(this);
    this.handleClearForm = this.handleClearForm.bind(this);
    this.handleValidationAlertClose = this.handleValidationAlertClose.bind(this); 
    this.handleValidationAlertOpen = this.handleValidationAlertOpen.bind(this); 
  }

  handleValidationAlertOpen(msg) {
    this.state.openValidationAlert = true;
    this.state.msgValidationAlert = msg;
    this.state.showProgress = false; 
    this.setState(this.state);
  }
  
  handleValidationAlertClose() {
    this.state.openValidationAlert = false;
    this.setState(this.state);
  }

  handleAlertClick = () => {
    this.state.openAlert = true;
    this.setState(this.state);
  };

  handleAlertClose = (event, reason) => {
    this.state.openAlert = false; 
    this.setState(this.state); 
  };

  handleSwitchExtJSON(e){
    this.state.extjson = !this.state.extjson; 
    this.setState(this.state);
  }

  handleSwitchMinInt(e){
    this.state.minIntSize = !this.state.minIntSize; 
    this.setState(this.state);
  }

  handleSwitchTruncInt(e){
    this.state.truncateInt = !this.state.truncateInt; 
    this.setState(this.state);
  }

  handleTextFieldTopName(e) {
    this.state.topname = e.target.value; 
    this.setState(this.state);
  }

  handleCodeChange(newValue){
    this.state.content = newValue;
  }

  handleFormSubmit(e) {
    e.preventDefault();
    this.state.showProgress = true; 
    this.setState(this.state);
    var content = "{}";
    try{
      content = JSON.parse(this.state.content);
    } catch(e) {
      this.handleValidationAlertOpen(
        "Please make sure the JSON document is in valid JSON format. You can use JSON formatting tool such as https://jsonlint.com/ to help with the formatting"
      );
      return;
    }
    var param = {
      "content": content, 
      "extjson": this.state.extjson, 
      "minintsize": this.state.minIntSize,
      "truncateint": this.state.truncateInt,
      "topname": this.state.topname,
    };
    console.log(param);
    fetch("/.netlify/functions/convert", {
        method:'POST', 
        mode:'cors',
        cache:'no-cache',
        headers: {'Content-Type': 'application/json'}, 
        redirect:'follow', 
        body: JSON.stringify(param)}
        ).then(response => {
          return response.json();
        }).then(result=>{
          console.log(result);
          this.state.output = result.output;
          this.state.showProgress = false;
          this.setState(this.state);
    }); 
  }

  handleCopyClipboard(e){
    e.preventDefault();
    navigator.clipboard.writeText(this.state.content);
    this.handleAlertClick(); 
  }

  handleClearForm(e) {
    e.preventDefault();
    this.state.output = ""
    this.state.content = "";
    this.setState(this.state);
  }

  render() {
    const { classes } = this.props;
    return (
      <div id="root">
      <form className="container-fluid" onSubmit={this.handleFormSubmit}>
        <div>
            <Grid container spacing={1}>
              <Grid item xs={2}>
                <Paper className={classes.paper}>
                <TextField
                    id="filled-topname"
                    label="Struct Name"
                    value={this.state.topname}
                    variant="outlined"
                    onChange={this.handleTextFieldTopName}
                  />
                  <br/><br/>
                  <FormControlLabel
                    value="extJSON"
                    control={<Switch 
                              color="primary" 
                              onClick={this.handleSwitchExtJSON}
                              checked={this.state.extjson}
                            />}
                    label="ExtJSON"
                    labelPlacement="end"
                  />
                  <br/>
                  <FormControlLabel
                    value="minIntSize"
                    control={<Switch 
                              color="primary" 
                              onClick={this.handleSwitchMinInt}
                              checked={this.state.minIntSize}
                            />}
                    label="Minimize Int"
                    labelPlacement="end"
                  />
                  <br/>
                  <FormControlLabel
                    value="truncateInt"
                    control={<Switch 
                              color="primary" 
                              onClick={this.handleSwitchTruncInt}
                              checked={this.state.truncateInt}
                            />}
                    label="Truncate Int"
                    labelPlacement="end"
                  />
                  <br/>
                  <div id="progress">
                    { this.state.showProgress ? <Progress/> : null}
                  </div>    
                  <br/>
                  <Button variant="contained" 
                          onClick={this.handleFormSubmit}
                          className={classes.button}
                  >
                  Convert
                  </Button>
                </Paper>    
              </Grid>

              <Grid item xs>
                <FormLabel>JSON</FormLabel>
                <IconButton color="primary" 
                            aria-label="Clear Input" 
                            component="span"
                            onClick={this.handleClearForm}>
                  <ReplayRoundedIcon />
                </IconButton>
                <AceEditor
                  mode="javascript"
                  theme="github"
                  name="input-code"
                  placeholder="Insert JSON document here. i.e. {&quot;foo&quot; : &quot;bar&quot; }"
                  onChange={this.handleCodeChange}
                  wrapEnabled={true}
                  width={ "100%" }
                  showPrintMargin={false}
                  showGutter={true}
                  highlightActiveLine={true}
                  value={this.state.content}
                  setOptions={{showLineNumbers: false, 
                              tabSize: 2, 
                              enableLiveAutocompletion: false, 
                              useWorker: false, 
                              behavioursEnabled: false}}
                />
              </Grid>
              <Grid item xs>
                <FormLabel>Go BSON</FormLabel>
                <IconButton color="primary" 
                            aria-label="Copy To Clipboard" 
                            component="span"
                            onClick={this.handleCopyClipboard}
                            >
                  <FileCopyRoundedIcon />
                </IconButton>
                <AceEditor
                  mode="golang"
                  theme="github"
                  name="output-code"
                  wrapEnabled={true}
                  width={ "100%" }
                  showPrintMargin={false}
                  showGutter={true}
                  highlightActiveLine={true}
                  value={this.state.output}
                  setOptions={{showLineNumbers: true, 
                              tabSize: 2, 
                              enableLiveAutocompletion: false, 
                              useWorker: false, 
                              readOnly: true,
                              behavioursEnabled: false}}
                />
              </Grid>
            </Grid>
              <AlertInputValidationDialog
                  handleClose={this.handleValidationAlertClose}
                  open={this.state.openValidationAlert}
                  message={this.state.msgValidationAlert}
              />
              <Snackbar open={this.state.openAlert} 
                        autoHideDuration={3000} 
                        onClose={this.handleAlertClose}
              >
                <Alert onClose={this.handleAlertClose} severity="info">
                  Copied to Clipboard!
                </Alert>
              </Snackbar>
        </div>
      </form>
      </div>
    );
  }
}

export default withStyles(styles)(FormContainer);
